// Premium Glass Theme - Design System
// Modern glass morphism with carmine + gold/copper accents

export const theme = {
  colors: {
    primary: {
      DEFAULT: '#960018',
      main: '#960018',
      light: '#C41E3A',
      dark: '#750012',
      bgSoft: '#FFF5F5',
    },
    accent: {
      gold: '#C5964A',
      goldLight: '#D4A76A',
      goldDark: '#A67B3D',
      copper: '#B87333',
      copperLight: '#D4956B',
    },
    secondary: {
      DEFAULT: '#0F172A',
      main: '#0F172A',
      light: '#1E293B',
      dark: '#020617',
      foreground: '#ffffff',
    },
    background: {
      default: '#F0F4F8',
      paper: '#FFFFFF',
      subtle: '#F1F5F9',
      dark: '#0F172A',
      surface: '#FFFFFF',
      glass: 'rgba(255, 255, 255, 0.72)',
      glassDark: 'rgba(15, 23, 42, 0.85)',
    },
    text: {
      primary: '#0F172A',
      secondary: '#475569',
      tertiary: '#94A3B8',
      muted: '#94A3B8',
      inverted: '#FFFFFF',
      gold: '#C5964A',
    },
    border: {
      default: '#E2E8F0',
      strong: '#CBD5E1',
      light: 'rgba(255, 255, 255, 0.18)',
      glass: 'rgba(255, 255, 255, 0.25)',
      focus: '#960018',
    },
    status: {
      success: '#10B981',
      successBg: '#ECFDF5',
      warning: '#F59E0B',
      warningBg: '#FFFBEB',
      error: '#EF4444',
      errorBg: '#FEF2F2',
      info: '#3B82F6',
      infoBg: '#EFF6FF',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    section: 48,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
    xxl: 24,
    full: 9999,
  },
  shadows: {
    sm: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 3,
      elevation: 1,
    },
    md: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    lg: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 20,
      elevation: 6,
    },
    glass: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 16,
      elevation: 4,
    },
    gold: {
      shadowColor: '#C5964A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 4,
    },
  },
  typography: {
    h1: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '700' as const,
      letterSpacing: -0.5,
      color: '#0F172A',
    },
    h2: {
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '600' as const,
      letterSpacing: -0.3,
      color: '#0F172A',
    },
    h3: {
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600' as const,
      color: '#0F172A',
    },
    subtitle1: {
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '600' as const,
      color: '#0F172A',
    },
    subtitle2: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500' as const,
      color: '#475569',
    },
    body: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '400' as const,
      color: '#475569',
    },
    body2: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '400' as const,
      color: '#64748B',
    },
    caption: {
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '500' as const,
      color: '#94A3B8',
    },
    label: {
      fontSize: 11,
      fontWeight: '600' as const,
      letterSpacing: 0.8,
      textTransform: 'uppercase' as const,
      color: '#94A3B8',
    },
  },
  components: {
    glassCard: {
      backgroundColor: 'rgba(255, 255, 255, 0.78)',
      borderRadius: 16,
      padding: 18,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.35)',
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 16,
      elevation: 3,
    },
    button: {
      primary: {
        backgroundColor: '#960018',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        flexDirection: 'row' as const,
      },
      gold: {
        backgroundColor: '#C5964A',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        flexDirection: 'row' as const,
      },
      secondary: {
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.6)',
        paddingVertical: 14,
        paddingHorizontal: 24,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        flexDirection: 'row' as const,
      },
    },
    input: {
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      borderWidth: 1,
      borderColor: 'rgba(226, 232, 240, 0.6)',
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: '#0F172A',
      height: 48,
    },
  },
};

// Asset URLs
export const assets = {
  heroBackground: 'https://images.unsplash.com/photo-1748946469988-61310d7ea26a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2NDN8MHwxfHNlYXJjaHwyfHxtb2Rlcm4lMjBmYWN0b3J5JTIwY29udmV5b3IlMjBiZWx0JTIwc3lzdGVtJTIwY2xlYW58ZW58MHx8fHwxNzczMDc3MzQyfDA&ixlib=rb-4.1.0&q=85',
  productPlaceholder: 'https://images.unsplash.com/photo-1764875471704-95de704ee3a2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTN8MHwxfHNlYXJjaHwyfHxtZXRhbCUyMGNvbnZleW9yJTIwcm9sbGVyfGVufDB8fHx8MTc3MzA3NzM1M3ww&ixlib=rb-4.1.0&q=85',
};

// Common styles for glass morphism
export const commonStyles = {
  screenContainer: {
    flex: 1,
    backgroundColor: '#F0F4F8',
  },
  screenHeader: {
    backgroundColor: '#0F172A',
    paddingTop: 56,
    paddingBottom: 22,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  screenHeaderTitle: {
    fontSize: 22,
    fontWeight: '700' as const,
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  screenHeaderSubtitle: {
    fontSize: 13,
    color: '#C5964A',
    marginTop: 4,
    fontWeight: '500' as const,
    letterSpacing: 0.3,
  },
  glassCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#0F172A',
    marginBottom: 14,
    letterSpacing: -0.2,
  },
  goldAccentLine: {
    width: 32,
    height: 3,
    backgroundColor: '#C5964A',
    borderRadius: 2,
    marginBottom: 8,
  },
};

export default theme;
